#19 Select Seats + Postgres
devhausleipzigacademy/camp12-midterm-backend pull request #22
Opened 2024-07-17 09:35 UTC by focusedXmind

## Checklist

Confirm you have completed the following actions prior to submitting this PR.

- [X] There is an existing issue report for this PR.
- [X] I have created a feature branch.
- [X] My changes have been committed.
- [X] I have pushed my changes to the branch.

## Description

When reserving seats, we need to POST them to the backend and add the reserved seats to our DB.

The task is about the modification of the functionality for reserving seats with postgres. The following points to do within the task were:

- hook up route to database
- get the current booked seats
- merge the booked seats with the new booked seats

Closes #19

2024-07-24 12:04 UTC, louziferr commented on prisma/seed.ts
> +const prisma = new PrismaClient();
please import prisma from "../lib/db" and don't create a new PrismaClient

2024-07-24 12:05 UTC, louziferr commented on prisma/seed.ts
Please also seed users and bookmarks (just like in the main branch).

2024-07-24 12:07 UTC, louziferr commented on prisma/seed.ts
> +  await Promise.all(
Please loop over seats with a for-loop and then await prisma.seat.create(...) . Just like with users in the main branch.


Please also seed ScreeningSeats.

2024-07-24 12:08 UTC, louziferr commented on routes/reservations.ts
> +const prisma = new PrismaClient();
Please import prisma from "../lib/db". Don't create a new PrismaClient.

2024-07-24 12:09 UTC, louziferr commented on routes/reservations.ts
> +
Please also check if the seat exists.

2024-07-24 12:09 UTC, louziferr requested changes
changes needed

2024-07-25 13:20 UTC, dnmct approved these changes

2024-07-25 13:20 UTC, dnmct commented on package.json
> +    "npm": "^10.8.2",
why did you install npm locally?

2024-07-25 13:23 UTC, merged