25 select date
devhausleipzigacademy/camp12-midterm-backend pull request #27
Opened 2024-07-18 07:35 UTC by Fredmpk

It now  uses date-fns to get all dates of the next 7 days, querys all times that match on the dates and filters the dates that have all seats booked as in your previous PR and returns an object with the dates as key and the times as values.

2024-07-22 08:05 UTC, dnmct requested changes

2024-07-22 08:05 UTC, dnmct commented on routes/times.ts
> +  const screenings = await sql<
Please use prisma

2024-07-24 08:30 UTC, louziferr commented on prisma/schema.prisma
> +  booked_seats String
Please use Camel Casing for field names.

2024-07-24 08:33 UTC, louziferr commented on prisma/seed.ts
> +      id: "e72f636c-7bcb-4c35-8b77-c1c066f9b0a1",
UUIDs are created by prisma, and should not be hard-coded.

2024-07-24 08:37 UTC, louziferr requested changes
small changes needed

2024-07-24 12:54 UTC, louziferr commented on prisma/schema.prisma
> +  bookedSeats String
bookedSeats should be an string array

2024-07-24 12:54 UTC, louziferr commented on prisma/seed.ts
> +      bookedSeats: "A1,B1,C1,D1,E1,F1",
bookedSeats should be a string array here as well

2024-07-24 13:25 UTC, louziferr commented on routes/times.ts
> +        if (screening.booked_seats.split(",").length < SeatsTotal) {
this causes an error. please fix :)

2024-07-25 13:13 UTC, dnmct approved these changes

2024-07-25 13:18 UTC, dnmct approved these changes

2024-07-25 13:18 UTC, merged